### ISSUE TITLE
Feature request:  Midi-QoL compatibility

### ISSUE THREAD

**Issue by notrealdan** [gsimon2/dramatic-rolls#1]
Could this be made compatible with midi-qol?  The sounds and confetti do trigger for me on manual d20 rolls (`/r 1d20` in chat, for example) that result in 1s or 20s, just not attacks made using midi-qol.  Thanks!
https://gitlab.com/tposney/midi-qol

**Comment by gsimon2** [comment]
Never used that module, but as I get time I will try to pull it down and look into what's going on. Thanks for bringing it to my attention!

**Comment by gsimon2** [comment]
Tested with:

- Dnd5e v1.2.2
- libWrapper v1.70
- Midi QOL v0.3.53
- Dramatic Rolls v1.0.0

Worked for me. This module triggers on the 'createChatMessage' hook, do you for anything else that could be stomping on this event?

**Comment by notrealdan** [comment]
I just tried again with a fresh world, a basic Orc actor from the default dnd5e SRD compendium, and just those modules enabled.  Still no sounds were getting triggered for me on natural 20s or 1s.  To make sure that the sounds weren't getting triggered, but also muted somehow, I enabled Confetti also to have a visual indicator also.  The Confetti was not getting triggered on natural 20 either.

After playing around with the settings in midi-qol, I think I found the culprit.  If the setting for "Merge Rolls to one card" is enabled, then the sounds and confetti do not get triggered.  Otherwise, they do.  I've included a screenshot of my midi-qol settings, highlighting the ones I changed, but I'm pretty sure it's that one setting that changes something relevant and causes this.  The resulting chat cards for attacks are very different than standard, so I guess it's not surprising that those rolls aren't noticed.

Hopefully it's easy enough to be able to trigger on those also, but I understand that compatibility with random other modules out there might not be where you want to spend you time.  :)  Thanks again for looking into this!

![Annotation 2021-01-18 090738](https://user-images.githubusercontent.com/28198633/104939242-6a05bb80-596d-11eb-9bc1-a931d91bb1a7.png)

**Comment by gsimon2** [comment]
Good find! I am strictly a Pathfinder 2e player, so DnD support slipped my testing, but that being said I would love for this module to be as generic as possible. So when I get time, I will look into making this compatible.

Thanks for reaching out and doing the research to find the culprit. Much appreciated!

**Comment by gsimon2** [comment]
This should now be fixed with the just released 1.0.2 version. Please try it out and confirm that you are no longer experiencing issues. Thanks!
