### ISSUE TITLE
Compatibility with 0.8.6

### ISSUE THREAD

**Issue by apoapostolov** [gsimon2/dramatic-rolls#12]
Due to changes in the sound API, now Dramatic Rolls plays no sound and throws errors.

**Comment by gsimon2** [comment]
Didn't see version `0.8.x` was pushed to `stable`. Will work on the compatibility fix. Thanks for bringing it to my attention!

**Comment by gsimon2** [comment]
Just release version `1.4.0`. This should now be compatible with Foundry versions `0.8.x`. Thanks for posting!
