### ISSUE TITLE
[REQUEST] Module Volume Control

### ISSUE THREAD

**Issue by ianm32** [gsimon2/dramatic-rolls#16]
It would be fantastic for the module itself to have a volume control for the sounds, as I can't seem to find a way to reduce the volume from outside the module.

**Comment by gsimon2** [comment]
Hey @ianm32, I just released version `1.6.0` of this module which includes the volume control functionality that you requested. Please check it out and let me know if it does not solve your needs. Thanks for posting!

**Comment by ianm32** [comment]
Perfect!  This works great.  I thought it was just going to be a global volume control, but you went and gave each sound its own, which is frankly even better!  Thanks so much.  👍
