### ISSUE TITLE
Feature Request: Quick-Roll support.

### ISSUE THREAD

**Issue by apoapostolov** [gsimon2/dramatic-rolls#2]
Similar to Midi-QoL but with a more flexible chat card for attacks.
Mod repository here: https://github.com/slcao2/FoundryVTT-QuickRolls

**Comment by gsimon2** [comment]
Opened a PR that should add support for the Quick Rolls module: https://github.com/gsimon2/dramatic-rolls/pull/3.

Will put it through the testing process as I get time and when / if it ships will follow up on this thread. Thanks for bringing the issue to my attention.

**Comment by gsimon2** [comment]
This is now has limited support for `quick-rolls`. Limited only because when using it with the `dice-so-nice` module and rolling with advantage or disadvantage, effects will trigger on both rolls (if both are either a crit or fumble).
