### ISSUE TITLE
PF2 crits support. 

### ISSUE THREAD

**Issue by apoapostolov** [gsimon2/dramatic-rolls#21]
Summary: In PF2, it is a critical success to roll 10 or more above DC ro AC, not only to hit 20 or 1 on the d20. Dramatic Roll doesn’t support that yet, but very simple chat-message listener could add support for PF2 criticals if the system is PF2e.  

### Support for PF2 Critical Hits

If a PF2 chat message contains “Result: Critical Hit” or Result: Critical Success”, play a Dramatic Roll the same way as natural 20. This can be any span element of class “criticalSuccess”

If a PF2 chat message contains “Result: Critical Miss” or “Result: Critical Failure”, play a Dramatic Roll the same way as natural 1. This can be any span element of class “criticalFailure”

Example code in a chat message:

```<div class="result degree-of-success" data-visibility="all">Result: **<span data-visibility="all" data-whose="self" class="criticalSuccess">Critical Success</span>** <span data-visibility="gm" data-whose="target">by +14</span></div>```

**Comment by gsimon2** [comment]
Hello!

Thanks for the feature request. It looks like the PF2E game system attaches the degree of success to the roll and I leveraged that to allow for override triggers of critical successes and failures. Please update to version `2.1.0` and enable the setting shown below. 

![image](https://user-images.githubusercontent.com/20954654/196037080-9edfd6eb-ff1a-4c1b-85a0-685ef0168e35.png)

Please feel free to open another issue if you have any further requests!

**Comment by 8bitjunkie** [comment]
I believe this issue is back after the v12 update (potentially before).

**Comment by gsimon2** [comment]
Appears to be working for me with Foundry `12.327` and pfe `6.0.0-beta2`.

Can you check the logs for any errors? 

https://github.com/gsimon2/dramatic-rolls/assets/20954654/a9c78a74-0ff1-4be1-84b3-41c01f9b8d67

**Comment by 8bitjunkie** [comment]
Sorry, I should have been more specific. It will not play a default or set sound on a failure of -10 or more, only on a natural 1. So, no active triggers on a degree of failure. 

![image](https://github.com/gsimon2/dramatic-rolls/assets/669735/08d49712-457b-4a1e-8493-3608965cde59)

**Comment by gsimon2** [comment]
Critically failing a check is still triggering the "fumble" sounds for me.

https://github.com/gsimon2/dramatic-rolls/assets/20954654/1106de49-aed8-49a2-a07b-b4725f4232a3

Failing an attack by 10 or more is also triggering the "fumble" sounds for me.

https://github.com/gsimon2/dramatic-rolls/assets/20954654/d1d799f4-0ef1-43f9-a1a0-14ac929bc9de

Can you ensure that you have version `2.5.1` of the module installed?

**Comment by 8bitjunkie** [comment]
Hi Glen - I have the latest build, as well as the latest pf2e on latest stable v12. I really appreciate you walking me through this. You are correct, I didn't make any changes but this is now working for me. I reran the tests you have above by exaggerating the AC on the target - That work...so then I honed target AC back in and just missed exactly by -10 (there is only 1 degree of failure, as well as a natural 1) and that also worked for me. I don't know, I am a competent foundry user but it is working for me now; I will mark this up as user error hah. Thank you for your patience and helping me through this!

**Comment by gsimon2** [comment]
@8bitjunkie 

Honestly not a problem! Helping out the community is why I make / maintain these modules. 

Feel free to open issues in the future if you have any other troubles or ideas for improvements!
