### ISSUE TITLE
"isPublicRoll" does not exist

### ISSUE THREAD

**Issue by MrVauxs** [gsimon2/dramatic-rolls#23]
* **FVTT version**: 10.288
* **DsN version**: 4.6.5
* **Dramatic Rolls version**: 2.1.0
* **System**: Pathfinder 2e 4.3.3
* **Step to reproduce**: Type anything into chat that isn't a dice roll.

![image](https://user-images.githubusercontent.com/32039708/199589840-86f0220e-42a8-41ff-b8e1-a419138147db.png)

**Comment by gsimon2** [comment]
Hey thanks for posting this. The issue would be resolved in version `2.1.1`.
