### ISSUE TITLE
Audio Preview Not Working - Uncaught TypeError: Cannot read properties of undefined (reading 'AudioHelper')

### ISSUE THREAD

**Issue by myzar472** [gsimon2/dramatic-rolls#29]
**Steps to Reproduce:**

1) FoundryVTT 11 Build 315, Latest PF2e System (5.16.1 at time of writing)
2) No other modules enabled except Dramatic Rolls (2.50 at time of writing)
3) Go to Settings and perform an audio preview of any sound. It will not play. Developer Tools will log an error (see below)

**Error Logs**

Uncaught TypeError: Cannot read properties of undefined (reading 'AudioHelper')
    at DramaticRollsSettingsForm.onPlaySound (settingsForm.js:174:21)
    at DramaticRollsSettingsForm.<anonymous> (settingsForm.js:88:33)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**Comment by gsimon2** [comment]
Sorry about this. They namespaced the AudioHelper in v12 and I didn't test the module against v11. Try  the `2.5.1` version of the module and let me know if you still have issues. Thanks for reporting the bug!
