### ISSUE TITLE
Custom Fumble sounds not playing – D&D 5E

### ISSUE THREAD

**Issue by Zalakoth** [gsimon2/dramatic-rolls#37]
As the title states, the custom fumble sounds I have uploaded for my game are no longer working. I am on the module v. 3.0.1 and D&D 5th Edition v. 3.3.1 (Foundry v12 Build 328)

**Comment by gsimon2** [comment]
@Zalakoth - I am unable to repro this locally (custom uploaded sounds seem to be working for both crits and fumbles for me).

Perhaps we can debug this if I can get some more information:
Do you have any errors appearing in the console when a fumble is rolled?  You can use `/r 1d20x>1kl` to force a natural one. 
What file formats are you using for the sounds?
Are you running Foundry locally or hosting using a service such as Forge?

**Comment by Zalakoth** [comment]
Updating to v.3.0.2 of the module seems to have fixed my problem. Figures that would happen the moment we try to debug it. Thank you anyhow :)

**Comment by gsimon2** [comment]
If you had all the animations disabled then it would make sense that your sounds were not playing. That is the bug I fixed in `3.0.2`, otherwise 🤷‍♂️ 

Glad its working now. Always feel free to post another issue if you run into anything else. Happy to help.
