### ISSUE TITLE
Crit and Fumble sounds not playing properly (Found a possible solution)

### ISSUE THREAD

**Issue by Cryptin0706** [gsimon2/dramatic-rolls#39]
Hello! I noticed recently that the sounds for crits and fumbles stopped working in my game. 
After doing some testing I found out that the apparent cause was due to me disabling all fumble and crit animations. I found that in order for the sounds to play, I needed to have at least one animation enabled.

**Comment by gsimon2** [comment]
Ah yea. I just refactored that chunk of code to support more animations and missed the edge case of having all the animations disabled but still wanting sound to play. Will hop on a fix shortly. Thanks for reporting the issue!

**Comment by gsimon2** [comment]
Sorry for the inconvenience. This should be fixed in version `3.0.2` which I just released. Thanks again!
