### ISSUE TITLE
Feature Request: Adding/Toggling Sound

### ISSUE THREAD

**Issue by InterruptingOctopus** [gsimon2/dramatic-rolls#4]
i was wondering if there would be an option to add our own custom sounds and also toggle which of the default sounds get played in respective rolls
such as us adding kefka's laugh to a nat 1 and the FF victory fanfare to a nat 20 or any other applicable sound effects fitting for the rolls

**Comment by DrWiFi** [comment]
I second the request to add custom sounds. I found the fail horn from the Price is Right is awesome for a nat 1. Still looking for the perfect Nat 20 sound though.
I would also like to request the option of ignoring NPC rolls. The players really only want to celebrate when they roll the crit, not when the npc's do.
Thanks!

**Comment by gsimon2** [comment]
This is something I wanted to do when first creating the repo, but a proper solution is a fair chunk of work. I will start piecing something together as I get time, but an actual release might take a while. In the mean time, you can hack the functionality on your own machines pretty easily, if interested.

Add the sounds files to either the crit or fumble sound directories, `dramatic-rolls/sounds/crit/` and /dramatic-rolls/sounds/fumble` respectively.  Then in `dramatic-rolls/src/soundEffectController.js` add the audio file names to either the `critSoundEffectFiles` array or the `fumbleSoundEffectFiles`. You can also remove any files from these list if you do not want them to play.

When I start getting a branch ready to do this using a menu, I will update this thread. Thanks for posting!

**Comment by InterruptingOctopus** [comment]
something i noticed doing what you suggested is that whenever the module updates, everyhing in its folders is reverted, including sound files, and the entries in the js file as well

**Comment by gsimon2** [comment]
Yes this is a good point. Sorry I should have made that clear when I initially posted.

**Comment by gsimon2** [comment]
Planning on beginning work on this feature this week. If you have any sound bites you would like to include in the module (for everyone to have access to) please provide them in a comment. Be mindful of potential copyright violations.

**Comment by gsimon2** [comment]
FYI - The ability of configure which sounds play on either a natural 20 or natural 1 have been added in the newly released 1.1.0 version. I have also added support for custom added sounds.

Thanks for posting!

**Comment by gsimon2** [comment]
> request the option of ignoring NPC rolls

This has been added as of version 1.2.0.
