### ISSUE TITLE
Feature Request: Custom Flair

### ISSUE THREAD

**Issue by simtudor** [gsimon2/dramatic-rolls#6]
It would be amazing if there were customizable buttons or Macros that could display an image or animation, like an animated Nat 1 on a critical.

**Comment by gsimon2** [comment]
[Dice So Nice](https://foundryvtt.com/packages/dice-so-nice/) actually has something like this built in. If you go to the configure settings -> My Dice Settings -> Special Effects. You can configure a number of animations on what ever dice results you want. They need an exception job with their animations so, at this time, I have no plans in adding custom animations to this module. Thanks for posting!
