### ISSUE TITLE
[BUG] cant add new files

### ISSUE THREAD

**Issue by PalaNolho** [gsimon2/dramatic-rolls#9]
Hi,

I'm not able to add new sounds to the critical and fumble settings.
when I click on the "add..." option it opens my system instead of the foundry file system.

This makes it impossible for me to add new sounds (**Note:** I'm using could hosting)

**Comment by gsimon2** [comment]
Hi @PalaNolho, sorry you are experiencing issues.

Could you provided a few screen shots and more information? Like what are you using for cloud hosting? I will be able to figure out the issue better if I can reproduce your setup. Thanks.

**Comment by PalaNolho** [comment]
Hope this will help
https://www.screencast.com/t/gXj9q5CtfcI

**Comment by gsimon2** [comment]
Awesome video! The issue is making sense to me. I have not messed with cloud hosting Foundry yet so was unfamiliar with the workflow. I will work on cutting a fix for this as I get some free time and will keep you updated.

**Comment by gsimon2** [comment]
@PalaNolho Hey had sometime to poke around at it and I think utilizing the FoundryVtt FilePicker should solve the issue for you. Please update to version `1.3.0` and let me know if this resolves the issue for you.

**Comment by PalaNolho** [comment]
@gsimon2 FYI, I see that there is a new 1.3.0 version and I see that the foundry page is also updated with it. 
But when I check for updates on the mobile, it's not picking up the new version.

Not sure if it's normal or not, but wanted to lt you know

**Comment by PalaNolho** [comment]
ok... now it's not working... 
now it doesn't play any sound at all when a crit or fumble is rolled.

already disabled modules to see who could be messing up but still nothing.
I don't see any error in console

**Comment by gsimon2** [comment]
What version of Foundry are you using?

**Comment by PalaNolho** [comment]
0.7.9
There is not yet any stable release for 0.8.x

**Comment by PalaNolho** [comment]
0.7.9

There is not yet any stable release for 0.8.0

- Miguel Pinto

**Comment by gsimon2** [comment]
This one is sending me for a loop. I have uninstalled the modules from my machine and did a clean re-install and they are working fine. Tested them across multiple existing worlds of different systems as well as new worlds. I am unable to reproduce your issue. I will continue exploring, but it may take me a bit to find a solution.

If you need a quicker fix, I would be willing to hop onto the Foundry Discord server and chat. We may be able to figure it out if we sit down and walk through the steps together, but scheduling my be tricky.

**Comment by PalaNolho** [comment]
I went to tet again and on a new world, I was able to play the sounds.... (even the ones I selected from my filesystem)

I went back to my original world and tried again, (disabled EVERYTHING except the confetties and the dramatic module) and still no sounds on 1 or 20.

I'm out of ideas why it works for one workd and not for another. I will be more than happy if you would like to have a look with me to see what is going one. i'm always in discord id you want to ping me there `palanolho#7943` :(

**Comment by gsimon2** [comment]
Can you do me a favor and check that the `Disable Dramatic Rolls for NPCs and GM` setting is not enabled for your non-working world? That will prevent rolls that are not associated with player owned tokens from triggering effects. I think I can hop on discord tonight probably around 6 or so eastern time. I will ping and see if we can link up.

**Comment by PalaNolho** [comment]
yes, it's not selected :) I remembered this setting and it was the first thing I checked. I even selected it, saved then unselected it again and saved again just in case...

> tonight probably around 6 or so eastern time

Sounds good, thanks!

**Comment by PalaNolho** [comment]
ok ... We found the problem :D which it seems it's intentional
The sounds and confetti (if integrated) will only trigger for public roll.

I consider this bug closed then.
